name: pastry_app
description: A Flutter application for pastry recipes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  path: ^1.8.3
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  cached_network_image: ^3.3.1
  flutter_platform_widgets: ^3.0.2
  pocketbase: ^0.18.0
  http: ^1.2.2
  image_picker: ^1.0.4
  permission_handler: ^10.2.0
  url_launcher: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  